### ISSUE TITLE
Constants in the angular 1.X way

### ISSUE THREAD

**Issue by johnnypesola** [OskarKlintrotSkolarbeteWP14/1dv450-oklib08-webbramverk#19]
I pretty sure you won't like this for some reason. But there is an angular 1.X way of defining constants. [Here is a good example](http://twofuckingdevelopers.com/2014/06/angularjs-best-practices-001-constants/) of that written by `two ****ing developers`. This saves you from [using lodash `assign` method](https://github.com/OskarKlintrotSkolarbeteWP14/1dv450-oklib08-webbramverk/blob/master/angularApp/client/app/scripts/constants.js#L1). Just a suggestion :+1:

**Comment by OskarKlintrot** [comment]
I like that way actually, I just had missed it! But, I still would need lodash since the reason behind doing it like that is to be able to easily have a [file that I don't push to GitHub](https://github.com/OskarKlintrotSkolarbeteWP14/1dv450-oklib08-webbramverk/blob/master/angularApp/client/app/scripts/secrets.js#L1-L3).
